# Generated by Django 5.1.6 on 2025-03-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
