# Generated by Django 5.1.4 on 2025-01-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDetails',
            new_name='TaskDetail',
        ),
    ]
